//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfSpider.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class conferencia
    {
        public conferencia()
        {
            this.edicaos = new HashSet<edicao>();
        }
    
        public int idConferencia { get; set; }
        public string sigla { get; set; }
        public string nome { get; set; }
        public bool enabled { get; set; }
    
        public virtual ICollection<edicao> edicaos { get; set; }
    }
}
