//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfSpider.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public int idConferencia { get; set; }
        public int ano { get; set; }
        public int idTipoData { get; set; }
        public System.DateTime data { get; set; }
        public int idTipoExtracao { get; set; }
    
        public virtual edicao edicao { get; set; }
        public virtual tipodata tipodata { get; set; }
        public virtual tipoextracao tipoextracao { get; set; }
    }
}
