//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfSpider.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class edicao
    {
        public edicao()
        {
            this.data = new HashSet<datum>();
            this.edicaotopicoes = new HashSet<edicaotopico>();
            this.urls = new HashSet<url>();
        }
    
        public int idConferencia { get; set; }
        public int ano { get; set; }
        public string query { get; set; }
        public string qualis { get; set; }
    
        public virtual conferencia conferencia { get; set; }
        public virtual ICollection<datum> data { get; set; }
        public virtual ICollection<edicaotopico> edicaotopicoes { get; set; }
        public virtual ICollection<url> urls { get; set; }
    }
}
