//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfSpider.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoextracao
    {
        public tipoextracao()
        {
            this.data = new HashSet<datum>();
            this.urls = new HashSet<url>();
        }
    
        public int idTipoExtracao { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<datum> data { get; set; }
        public virtual ICollection<url> urls { get; set; }
    }
}
