//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfSpider.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipodata
    {
        public tipodata()
        {
            this.data = new HashSet<datum>();
            this.tipodata1 = new HashSet<tipodata>();
        }
    
        public int idTipoData { get; set; }
        public string descricao { get; set; }
        public int idTipoDataPai { get; set; }
    
        public virtual ICollection<datum> data { get; set; }
        public virtual ICollection<tipodata> tipodata1 { get; set; }
        public virtual tipodata tipodata2 { get; set; }
    }
}
